### ISSUE TITLE
Its required git hub id password in termux


### ISSUE THREAD

**Issue by Yudhi-sthir** [TermuxHackz/anonphisher#3]

**Comment by Samu23** [comment]
Perhaps, you have typed wrong repo
Check and try again

**Comment by TermuxHackz** [comment]
Check the repo again
Type git clone https://github.com/TermuxHackz/anonphisher

Be sure you check your spelling

**Comment by Yudhi-sthir** [comment]
I m just copy and paste

**Comment by TermuxHackz** [comment]
Send image

**Comment by Yudhi-sthir** [comment]
![Screenshot_2021-04-15-18-51-21-579_com.termux.jpg](https://user-images.githubusercontent.com/79323086/114876098-8343ca00-9ded-11eb-99c3-8662f05d1540.jpg)

**Comment by TermuxHackz** [comment]
I have seen the error
Check last letter
Letter "r" is missing after anonphisher

Its anonphisher not anonphishe

Type <code>cd $HOME</code> 
<br>
Then type <code>rm -rf anonphisher</code>
<br>

Then type 
```
git clone https://github.com/TermuxHackz/anonphisher

**Comment by TermuxHackz** [comment]
![IMG_20210416_133521](https://user-images.githubusercontent.com/70668507/115025004-b901b500-9eb8-11eb-8d90-e67e54a73733.png)

As u see in the image, letter "r" is missing
After "e"

**Comment by Yudhi-sthir** [comment]
Its dose not work when copy pest
Its work when type full link
Now installed anonphisher thank you 😊😊

**Comment by Yudhi-sthir** [comment]
Can we crack wifi password through termux
Pls help

**Comment by TermuxHackz** [comment]
Yes and no, if your termux is rooted, then yes you can, and if its not, you can't

**Comment by Anshusaini776676544e** [comment]
**ANSHU SAINI**
PASS
